model_name_or_path: "/workspace/models/LLM-Research/Qwen3-1.7B"
template: "qwen"
dataset_dir: "/workspace/project/data/stage2_cot_datasets"
dataset: "richere_full_split1_oracle_mixed_noise_top10_shuffle_sar_confrare10_typerolelite_train"
eval_dataset: "richere_full_split1_oracle_mixed_noise_top10_shuffle_sar_confrare10_typerolelite_dev_seen"
output_dir: "/workspace/project/outputs/stage2_full_sft_runs_stepmatch_user/richere_full_split1_qwen3_1_7b_instruct_oracle_mixed_noise_top10_shuffle_sar_confrare10_typerolelite_full"
stage: "sft"
do_train: true
overwrite_cache: true
preprocessing_num_workers: 8
save_strategy: "epoch"
eval_strategy: "epoch"
logging_steps: 5
report_to: "none"
finetuning_type: "full"
cutoff_len: 1024
max_samples: 10000
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
packing: false
learning_rate: 0.00001
warmup_ratio: 0.03
bf16: true
val_size: 0.0
eval_steps: 10
do_eval: true
save_only_model: true
num_train_epochs: 16.0
