model_name_or_path: /workspace/models/LLM-Research/Qwen3-1.7B
template: qwen
dataset_dir: /workspace/project/data/stage2_adaptive_datasets
dataset: richere_balanced_split1_oracle_mixed_noise_top10_shuffle_adaptive_outcome15cal_nlltop15_type_role_hint_plan_lite_routeaux2x_reasonos2_train_pos
eval_dataset: richere_balanced_split1_oracle_mixed_noise_top10_shuffle_adaptive_outcome15cal_nlltop15_type_role_hint_plan_lite_routeaux2x_reasonos2_dev_seen_pos
output_dir: /workspace/project/outputs/stage2_adaptive_runs_user/richere_split1_qwen3_1_7b_instruct_oracle_mixed_noise_top10_shuffle_adaptive_outcome15cal_nlltop15_type_role_hint_plan_lite_routeaux2x_reasonos2_full
stage: sft
do_train: true
overwrite_cache: true
preprocessing_num_workers: 8
save_strategy: epoch
eval_strategy: epoch
logging_steps: 5
report_to: none
finetuning_type: full
cutoff_len: 1024
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
packing: false
learning_rate: 1.0e-05
warmup_ratio: 0.03
bf16: true
val_size: 0.0
eval_steps: 10
do_eval: true
save_only_model: true
num_train_epochs: 8.0
load_best_model_at_end: false
