model_name_or_path: /workspace/project/outputs/stage2_full_sft_runs_stepmatch_user/richere_split1_qwen3_4b_gollie_style_direct_full/checkpoint-2064
template: qwen
dataset_dir: /workspace/project/data/stage2_adaptive_datasets
dataset: richere_balanced_split1_gollie_style_top10_shuffle_adaptive_hybrid_sgcot_thinking_evidence_cot_train_pos
eval_dataset: richere_balanced_split1_gollie_style_top10_shuffle_adaptive_hybrid_sgcot_thinking_evidence_cot_dev_seen_pos
output_dir: /workspace/project/outputs/stage2_adaptive_runs_user/richere_split1_qwen3_4b_gollie_style_adaptive_hybrid_sgcot_thinking_evidence_cot_full
stage: sft
do_train: true
overwrite_cache: true
preprocessing_num_workers: 8
save_strategy: epoch
eval_strategy: epoch
logging_steps: 1
report_to: none
finetuning_type: full
cutoff_len: 2048
max_samples: 20000
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
packing: false
learning_rate: 2.0e-06
warmup_ratio: 0.05
bf16: true
val_size: 0.0
eval_steps: 10
do_eval: true
save_only_model: true
num_train_epochs: 3.0
load_best_model_at_end: false
deepspeed: /workspace/project/configs/deepspeed/zero2_optimizer_offload_cpu.json
