#!/usr/bin/env bash
# E85 - second-teacher SG-CoT (teacher robustness). Same reasoning recipe + SAME sampled rows
# as E81 (seed 8101), but the reasoning is generated by a DIFFERENT teacher (deepseek-v4-pro
# instead of glm-5.1). Verifier is deepseek-v4-pro (glm-5.1 endpoint is down); the gold-only
# label + model-independent hard verifier remain the primary quality gate.
set -euo pipefail
cd /mnt/disk/gaojun/research/progressive-ee

LIMIT="${1:-1500}"
PROMPT_PROFILE="e81_trigger_locked_arbitration"
SEED=8101   # same as E81 -> same sampled rows, isolating the teacher change

if [ "${LIMIT}" -lt 50 ]; then
  RUN_NAME="e85_secondteacher_trigger_locked_arbitration_deepseek_smoke${LIMIT}"
  OUT_DIR="outputs/stage2_strategy_cot_e85/richere_e85_secondteacher_deepseek_smoke${LIMIT}_20260618"
else
  RUN_NAME="e85_secondteacher_trigger_locked_arbitration_deepseek_full1500"
  OUT_DIR="outputs/stage2_strategy_cot_e85/richere_e85_secondteacher_deepseek_full1500_20260618"
fi

MANIFEST="${OUT_DIR}/e76_manifest_rows.jsonl"
export OPENAI_API_KEY="${OPENAI_API_KEY:?Set OPENAI_API_KEY before running}"

python3 scripts/build_e76_contrastive_manifest_20260614.py \
  --output_dir "${OUT_DIR}" \
  --seed "${SEED}"

python3 scripts/generate_strategy_variants_cot_e47_20260606.py \
  --run_name "${RUN_NAME}" \
  --limit "${LIMIT}" \
  --seed "${SEED}" \
  --workers 16 \
  --base_url ${LLM_BASE_URL} \
  --model deepseek-v4-pro \
  --reasoning_effort max \
  --verifier_model deepseek-v4-pro \
  --verifier_reasoning_effort max \
  --prompt_profile "${PROMPT_PROFILE}" \
  --output_protocol xml_tags \
  --gen_max_tokens 8192 \
  --verify_max_tokens 1800 \
  --timeout 600 \
  --sampled_rows_path "${MANIFEST}" \
  --output_dir "${OUT_DIR}" \
  "${@:2}"
