model_name_or_path: "/workspace/models/LLM-Research/Llama-3.2-3B-Instruct"
template: "llama3"
dataset_dir: "/workspace/project/data/stage2_formal_datasets"
dataset: "richere_balanced_split1_predicted_top10_train_pos"
eval_dataset: "richere_balanced_split1_predicted_top10_dev_seen_pos"
output_dir: "/workspace/project/outputs/stage2_full_sft_runs_epoch20/richere_split1_llama3_2_3b_instruct_predicted_top10_direct_full"
stage: "sft"
do_train: true
overwrite_cache: true
preprocessing_num_workers: 8
save_strategy: "epoch"
eval_strategy: "epoch"
logging_steps: 5
report_to: "none"
finetuning_type: "full"
cutoff_len: 1024
max_samples: 10000
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
packing: false
learning_rate: 1e-05
warmup_ratio: 0.03
bf16: true
val_size: 0.0
eval_steps: 10
do_eval: true
save_only_model: true
num_train_epochs: 20.0
